主分支的工作流描述文件 - The workflow description file for the main
版本号 - Version 3.0.0
日期 - 2024.4.23

更新日志 - Update Logs
1.修复 VC、Net运行库无法下载的bug
2.优化 更新逻辑
3.优化 检测错误逻辑
4.增加 debug模式
5.修复 修复epic与RL环境时无法返回主菜单而被迫重启的问题
6.修复 多个菜单返回时出现进行下一步的问题
7.增加 日志监控体系(本地，不上传)
8.优化 异步体系，针对更多场景进行优化
9.升级 7z依赖已更新至24.04 beta
10.升级 aria2依赖已更新至1.37.0
