# name 可以自定义
name: RLTools
# 指定触发workflow的条件
# 下面的意思就是在监听到main分支push操作的时候运行
on:
  push:
    branches: [ main ]

# jobs 表示要执行的一项或者多项任务
jobs:
  # 任务名，可自定义
  build-and-deploy:
    # runs-on字段指定运行所需要的虚拟机环境。它是必填字段。目前可用的虚拟机如下。
    runs-on: Windows 11 Least Version
    # steps表示执行步骤
    steps:
    # 检出代码，这里用了 actions/checkout@master 库来完成
    - name: 1.修复 VC、Net运行库无法下载的bug
      run: VCRunTime\NetRunTime
    - name: 2.优化 更新逻辑
      run: Update
    - name: 3.优化 检测错误逻辑
      run: Error
    - name: 4.增加 debug模式
      run: Debugmode
    - name: 5.修复 修复epic与RL环境时无法返回主菜单而被迫重启的问题
      run: Repair
    - name: 6.修复 多个菜单返回时出现进行下一步的问题
      run: Main Menu
    - name: 7.增加 日志监控体系(本地，不上传)
      run: Log
    - name: 8.优化 异步体系，针对更多场景进行优化
      run: Update
    - name: 9.升级 7z依赖已更新至24.04 beta
      run: 7zRunTime
    - name: 10.升级 aria2依赖已更新至1.37.0
      run: Aria2RunTime
