  Job Description:
    Daily Update:
      Version: 3.0.0
      date: 2024.4.23
      runs-on: Windows 11 Least Version
        on:
          steps:
            # 更新日志
            - name: 1.修复 VC、Net运行库无法下载的bug
            - name: 2.优化 更新逻辑
            - name: 3.优化 检测错误逻辑
            - name: 4.增加 debug模式
            - name: 5.修复 修复epic与RL环境时无法返回主菜单而被迫重启的问题
            - name: 6.修复 多个菜单返回时出现进行下一步的问题
            - name: 7.增加 日志监控体系(本地，不上传)
            - name: 8.优化 异步体系，针对更多场景进行优化
            - name: 9.升级 7z依赖已更新至24.04 beta
            - name: 10.升级 aria2依赖已更新至1.37.0
